export const CREATE_DEPARTMENT_LIST_REQUESTED = 'create/CREATE_DEPARTMENT_LIST_REQUESTED';
export const CREATE_DEPARTMENT_LIST_SUCCEEDED = 'create/CREATE_DEPARTMENT_LIST_SUCCEEDED';
export const CREATE_DEPARTMENT_LIST_FAILED = 'create/CREATE_DEPARTMENT_LIST_FAILED';

export const CREATE_LEGION_LIST_REQUESTED = 'create/CREATE_LEGION_LIST_REQUESTED';
export const CREATE_LEGION_LIST_SUCCEEDED = 'create/CREATE_LEGION_LIST_SUCCEEDED';
export const CREATE_LEGION_LIST_FAILED = 'create/CREATE_LEGION_LIST_FAILED';

export const CREATE_LOANCHANNEL_LIST_REQUESTED = 'create/CREATE_LOANCHANNEL_LIST_REQUESTED';
export const CREATE_LOANCHANNEL_LIST_SUCCEEDED = 'create/CREATE_LOANCHANNEL_LIST_SUCCEEDED';
export const CREATE_LOANCHANNEL_LIST_FAILED = 'create/CREATE_LOANCHANNEL_LIST_FAILED';

export const CREATE_LOAN_REQUESTED = 'create/CREATE_LOAN_REQUESTED';
export const CREATE_LOAN_SUCCEEDED = 'create/CREATE_LOAN_SUCCEEDED';
export const CREATE_LOAN_FAILED = 'create/CREATE_LOAN_FAILED';

export default{
    CREATE_DEPARTMENT_LIST_REQUESTED,
    CREATE_DEPARTMENT_LIST_SUCCEEDED,
    CREATE_DEPARTMENT_LIST_FAILED,
    CREATE_LEGION_LIST_REQUESTED,
    CREATE_LEGION_LIST_SUCCEEDED,
    CREATE_LEGION_LIST_FAILED,
    CREATE_LOANCHANNEL_LIST_REQUESTED,
    CREATE_LOANCHANNEL_LIST_SUCCEEDED,
    CREATE_LOANCHANNEL_LIST_FAILED,
    CREATE_LOAN_REQUESTED,
    CREATE_LOAN_SUCCEEDED,
    CREATE_LOAN_FAILED,
}