export const LOGIN_REQUESTED = 'login/LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'login/LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'login/LOGIN_FAILED';

export const LOGOUT_REQUESTED = 'login/LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'login/LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'login/LOGOUT_FAILED';

export const GET_CURRENT_USER_REQUESTED = 'login/GET_CURRENT_USER_REQUESTED';
export const GET_CURRENT_USER_SUCCEEDED = 'login/GET_CURRENT_USER_SUCCEEDED';
export const GET_CURRENT_USER_FAILED = 'login/GET_CURRENT_USER_FAILED';

export default{
    LOGIN_REQUESTED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGOUT_REQUESTED,
    LOGOUT_SUCCEEDED,
    LOGOUT_FAILED,
    GET_CURRENT_USER_REQUESTED,
    GET_CURRENT_USER_SUCCEEDED,
    GET_CURRENT_USER_FAILED,
}