export const DETAIL_LOAN_LIST_REQUESTED = 'DETAIL/DETAIL_LOAN_LIST_REQUESTED';
export const DETAIL_LOAN_LIST_SUCCEEDED = 'DETAIL/DETAIL_LOAN_LIST_SUCCEEDED';
export const DETAIL_LOAN_LIST_FAILED = 'DETAIL/DETAIL_LOAN_LIST_FAILED';

export const DETAIL_DEPARTMENT_LIST_REQUESTED = 'DETAIL/DETAIL_DEPARTMENT_LIST_REQUESTED';
export const DETAIL_DEPARTMENT_LIST_SUCCEEDED = 'DETAIL/DETAIL_DEPARTMENT_LIST_SUCCEEDED';
export const DETAIL_DEPARTMENT_LIST_FAILED = 'DETAIL/DETAIL_DEPARTMENT_LIST_FAILED';

export const DETAIL_LEGION_LIST_REQUESTED = 'DETAIL/DETAIL_LEGION_LIST_REQUESTED';
export const DETAIL_LEGION_LIST_SUCCEEDED = 'DETAIL/DETAIL_LEGION_LIST_SUCCEEDED';
export const DETAIL_LEGION_LIST_FAILED = 'DETAIL/DETAIL_LEGION_LIST_FAILED';

export const DETAIL_LOANCHANNEL_LIST_REQUESTED = 'DETAIL/DETAIL_LOANCHANNEL_LIST_REQUESTED';
export const DETAIL_LOANCHANNEL_LIST_SUCCEEDED = 'DETAIL/DETAIL_LOANCHANNEL_LIST_SUCCEEDED';
export const DETAIL_LOANCHANNEL_LIST_FAILED = 'DETAIL/DETAIL_LOANCHANNEL_LIST_FAILED';

export const DETAIL_CLEAN_TABLE = 'DETAIL/DETAIL_CLEAN_TABLE';

export default{
    DETAIL_LOAN_LIST_REQUESTED,
    DETAIL_LOAN_LIST_SUCCEEDED,
    DETAIL_LOAN_LIST_FAILED,
    DETAIL_DEPARTMENT_LIST_REQUESTED,
    DETAIL_DEPARTMENT_LIST_SUCCEEDED,
    DETAIL_DEPARTMENT_LIST_FAILED,
    DETAIL_LEGION_LIST_REQUESTED,
    DETAIL_LEGION_LIST_SUCCEEDED,
    DETAIL_LEGION_LIST_FAILED,
    DETAIL_LOANCHANNEL_LIST_REQUESTED,
    DETAIL_LOANCHANNEL_LIST_SUCCEEDED,
    DETAIL_LOANCHANNEL_LIST_FAILED,
    DETAIL_CLEAN_TABLE,
}