export const BATCH_LOAN_LIST_REQUESTED = 'batch/BATCH_LOAN_LIST_REQUESTED';
export const BATCH_LOAN_LIST_SUCCEEDED = 'batch/BATCH_LOAN_LIST_SUCCEEDED';
export const BATCH_LOAN_LIST_FAILED = 'batch/BATCH_LOAN_LIST_FAILED';

export const BATCH_DEPARTMENT_LIST_REQUESTED = 'batch/BATCH_DEPARTMENT_LIST_REQUESTED';
export const BATCH_DEPARTMENT_LIST_SUCCEEDED = 'batch/BATCH_DEPARTMENT_LIST_SUCCEEDED';
export const BATCH_DEPARTMENT_LIST_FAILED = 'batch/BATCH_DEPARTMENT_LIST_FAILED';

export const BATCH_LEGION_LIST_REQUESTED = 'batch/BATCH_LEGION_LIST_REQUESTED';
export const BATCH_LEGION_LIST_SUCCEEDED = 'batch/BATCH_LEGION_LIST_SUCCEEDED';
export const BATCH_LEGION_LIST_FAILED = 'batch/BATCH_LEGION_LIST_FAILED';

export const BATCH_LOANCHANNEL_LIST_REQUESTED = 'batch/BATCH_LOANCHANNEL_LIST_REQUESTED';
export const BATCH_LOANCHANNEL_LIST_SUCCEEDED = 'batch/BATCH_LOANCHANNEL_LIST_SUCCEEDED';
export const BATCH_LOANCHANNEL_LIST_FAILED = 'batch/BATCH_LOANCHANNEL_LIST_FAILED';

export const BATCH_CLEAN_TABLE = 'batch/BATCH_CLEAN_TABLE';

export default{
    BATCH_LOAN_LIST_REQUESTED,
    BATCH_LOAN_LIST_SUCCEEDED,
    BATCH_LOAN_LIST_FAILED,
    BATCH_DEPARTMENT_LIST_REQUESTED,
    BATCH_DEPARTMENT_LIST_SUCCEEDED,
    BATCH_DEPARTMENT_LIST_FAILED,
    BATCH_LEGION_LIST_REQUESTED,
    BATCH_LEGION_LIST_SUCCEEDED,
    BATCH_LEGION_LIST_FAILED,
    BATCH_LOANCHANNEL_LIST_REQUESTED,
    BATCH_LOANCHANNEL_LIST_SUCCEEDED,
    BATCH_LOANCHANNEL_LIST_FAILED,
    BATCH_CLEAN_TABLE
}